service: DropDown-Demo
useDotenv: true

plugins:
  - serverless-dotenv-plugin

provider:
  lambdaHashingVersion: '20201221'
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  timeout: 10
  logRetentionInDays: 30
  stage: dev
  region: ap-northeast-1
  # profile: mindbank

functions:
  api:
    handler: lambda.universal
    events:
      - http: ANY /{proxy+}
      - http: ANY /